from taggit.tests.tests import (TaggableManagerTestCase, 
                                TaggableManagerDirectTestCase,
                                TaggableFormTestCase,
                                TaggableFormDirectTestCase,
                                TestParseTagInput,
                                TestTagPostProcessing,
                                TestFilterTags,
                                TestTagNormalization,
                                TestTagSynonyms,
                                TestEditStringForTags)
